package alfheim.common.integration.thaumcraft.handler;

import static alfheim.common.core.registry.AlfheimBlocks.*;
import static alfheim.common.core.registry.AlfheimItems.*;
import static alfheim.common.integration.thaumcraft.ThaumcraftAlfheimModule.*;
import static vazkii.botania.common.item.ModItems.*;

import alfheim.common.core.registry.AlfheimItems;
import net.minecraft.item.ItemStack;
import thaumcraft.api.ThaumcraftApi;
import thaumcraft.api.aspects.Aspect;
import thaumcraft.api.aspects.AspectList;

public class TCHandlerAspects {
	
	public static void addAspects() {
		ThaumcraftApi.registerObjectTag(new ItemStack(alfheimThaumOre, 1, 0),	(new AspectList())	.add(Aspect.getAspect("terra"),			1)	.add(Aspect.getAspect("metallum"),		2)	.add(Aspect.getAspect("permutatio"),	2)	.add(Aspect.getAspect("venenum"),		1)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(alfheimThaumOre, 1, 7),	(new AspectList())	.add(Aspect.getAspect("terra"),			1)	.add(Aspect.getAspect("vinculum"),		3)	.add(Aspect.getAspect("vitreus"),		2)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(alfheimThaumOre, 1, 1),	(new AspectList())	.add(Aspect.getAspect("terra"),			1)	.add(Aspect.getAspect("aer"),			3)	.add(Aspect.getAspect("vitreus"),		2)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(alfheimThaumOre, 1, 2),	(new AspectList())	.add(Aspect.getAspect("terra"),			1)	.add(Aspect.getAspect("ignis"),			3)	.add(Aspect.getAspect("vitreus"),		2)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(alfheimThaumOre, 1, 3),	(new AspectList())	.add(Aspect.getAspect("terra"),			1)	.add(Aspect.getAspect("aqua"),			3)	.add(Aspect.getAspect("vitreus"),		2)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(alfheimThaumOre, 1, 4),	(new AspectList())	.add(Aspect.getAspect("terra"),			1)	.add(Aspect.getAspect("terra"),			3)	.add(Aspect.getAspect("vitreus"),		2)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(alfheimThaumOre, 1, 5),	(new AspectList())	.add(Aspect.getAspect("terra"),			1)	.add(Aspect.getAspect("ordo"),			3)	.add(Aspect.getAspect("vitreus"),		2)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(alfheimThaumOre, 1, 6),	(new AspectList())	.add(Aspect.getAspect("terra"),			1)	.add(Aspect.getAspect("perditio"),		3)	.add(Aspect.getAspect("vitreus"),		2)	);
		
		ThaumcraftApi.registerObjectTag(new ItemStack(elvenOres, 1, 0),			(new AspectList())	.add(Aspect.getAspect("praecantatio"),	1)	.add(Aspect.getAspect("terra"),			1)	.add(Aspect.getAspect("lucrum"),		3)	.add(Aspect.getAspect("vitreus"),	 	3)	);	// dragonstone
		ThaumcraftApi.registerObjectTag(new ItemStack(elvenOres, 1, 1),			(new AspectList())	.add(Aspect.getAspect("praecantatio"),	1)	.add(Aspect.getAspect("terra"),			1)	.add(Aspect.getAspect("metallum"),		3)	);												// elementium
		ThaumcraftApi.registerObjectTag(new ItemStack(elvenOres, 1, 2),			(new AspectList())	.add(Aspect.getAspect("praecantatio"),	1)	.add(Aspect.getAspect("terra"),			1)	.add(Aspect.getAspect("vitreus"),		3)	);												// quartz
		ThaumcraftApi.registerObjectTag(new ItemStack(elvenOres, 1, 3),			(new AspectList())	.add(Aspect.getAspect("praecantatio"),	1)	.add(Aspect.getAspect("terra"),			1)	.add(Aspect.getAspect("lucrum"),		1)	.add(Aspect.getAspect("metallum"),		2)	);	// gold
		ThaumcraftApi.registerObjectTag(new ItemStack(elvenOres, 1, 4),			(new AspectList())	.add(Aspect.getAspect("praecantatio"),	1)	.add(Aspect.getAspect("terra"),			1)	.add(Aspect.getAspect("sensus"),		3)	);												// iffesal
		ThaumcraftApi.registerObjectTag(new ItemStack(livingcobble), 			(new AspectList())	.add(Aspect.getAspect("perditio"), 		1)	.add(Aspect.getAspect("terra"),			1)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(elvenSand),				(new AspectList())	.add(Aspect.getAspect("perditio"), 		1)	.add(Aspect.getAspect("terra"),			1)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(dreamLog),				(new AspectList())	.add(Aspect.getAspect("arbor"),			4)	.add(Aspect.getAspect("herba"),			4)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(dreamLeaves),				(new AspectList())	.add(Aspect.getAspect("herba"),			1)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(dreamSapling),			(new AspectList())	.add(Aspect.getAspect("arbor"),			1)	.add(Aspect.getAspect("herba"),			2)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(redFlame),				(new AspectList())	.add(Aspect.getAspect("ignis"),			16)	.add(Aspect.getAspect("perditio"),		16)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(poisonIce),				(new AspectList())	.add(Aspect.getAspect("gelum"),			16)	.add(Aspect.getAspect("ordo"),			16)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(manaInfuser),				(new AspectList())	.add(Aspect.getAspect("fabrico"),		5)	.add(Aspect.getAspect("metallum"),		10)	.add(Aspect.getAspect("ordo"),			4)	.add(Aspect.getAspect("permutatio"),	4)	.add(Aspect.getAspect("praecantatio"),	16)	.add(Aspect.getAspect("terra"),			4)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(alfheimPortal),			(new AspectList())	.add(Aspect.getAspect("auram"),			2)	.add(Aspect.getAspect("arbor"),			8)	.add(Aspect.getAspect("iter"),			4)	.add(Aspect.getAspect("metallum"),		4)	.add(Aspect.getAspect("praecantatio"),	8)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(tradePortal),				(new AspectList())	.add(Aspect.getAspect("iter"),			4)	.add(Aspect.getAspect("metallum"),		1)	.add(Aspect.getAspect("praecantatio"),	4)	.add(Aspect.getAspect("terra"),			6)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(elvoriumBlock),			(new AspectList())	.add(Aspect.getAspect("alienis"),		6)	.add(Aspect.getAspect("lucrum"),		20)	.add(Aspect.getAspect("metallum"),		27)	.add(Aspect.getAspect("praecantatio"),	54)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(mauftriumBlock),			(new AspectList())	.add(Aspect.getAspect("auram"),			64)	.add(Aspect.getAspect("alienis"),		64)	.add(Aspect.getAspect("lucrum"),		64)	.add(Aspect.getAspect("metallum"),		54)	.add(Aspect.getAspect("potentia"),		64)	.add(Aspect.getAspect("praecantatio"),	64)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(anyavil),					(new AspectList())	.add(Aspect.getAspect("lucrum"),		10)	.add(Aspect.getAspect("metallum"),		46)	.add(Aspect.getAspect("praecantatio"),	52)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(animatedTorch),			(new AspectList())	.add(Aspect.getAspect("motus"),			1)	.add(Aspect.getAspect("potentia"),		1)	.add(Aspect.getAspect("machina"),		1)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(itemHolder),				(new AspectList())	.add(Aspect.getAspect("terra"),			4)	.add(Aspect.getAspect("potentia"),		2)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(anomaly),					(new AspectList())	.add(Aspect.getAspect("alienis"),		8)	.add(Aspect.getAspect("potentia"),		2)	.add(Aspect.getAspect("perditio"),		2)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(alfheimPylon, 1, 0),		(new AspectList())	.add(Aspect.getAspect("metallum"),		6)	.add(Aspect.getAspect("praecantatio"),	12)	.add(Aspect.getAspect("vitreus"),		4)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(alfheimPylon, 1, 1),		(new AspectList())	.add(Aspect.getAspect("auram"),			2)	.add(Aspect.getAspect("metallum"),		6)	.add(Aspect.getAspect("potentia"),		2)	.add(Aspect.getAspect("praecantatio"),	12)	.add(Aspect.getAspect("vitreus"),		4)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(alfheimPylon, 1, 2),		(new AspectList())	.add(Aspect.getAspect("spiritus"),		2)	.add(Aspect.getAspect("metallum"),		6)	.add(Aspect.getAspect("potentia"),		6)	.add(Aspect.getAspect("praecantatio"),	12)	.add(Aspect.getAspect("vitreus"),		4)	.add(Aspect.getAspect("alienis"),		3)	);
		
		ThaumcraftApi.registerObjectTag(new ItemStack(elvenResource, 1, 0),		(new AspectList())	.add(Aspect.getAspect("alienis"),		8)	.add(Aspect.getAspect("iter"),			4)	.add(Aspect.getAspect("lux"),			8)	.add(Aspect.getAspect("ordo"),			8)	.add(Aspect.getAspect("praecantatio"),	8)	);												// Intercore
		ThaumcraftApi.registerObjectTag(new ItemStack(elvenResource, 1, 1),		(new AspectList())	.add(Aspect.getAspect("lucrum"),		4)	.add(Aspect.getAspect("metallum"),		6)	.add(Aspect.getAspect("potentia"),		4)	.add(Aspect.getAspect("praecantatio"),	6)	);																							// Infuscore
		ThaumcraftApi.registerObjectTag(new ItemStack(elvenResource, 1, 2),		(new AspectList())	.add(Aspect.getAspect("alienis"),		1)	.add(Aspect.getAspect("lucrum"),		3)	.add(Aspect.getAspect("metallum"),		4)	.add(Aspect.getAspect("praecantatio"),	8)	);																							// Elvorium
		ThaumcraftApi.registerObjectTag(new ItemStack(elvenResource, 1, 3),		(new AspectList())	.add(Aspect.getAspect("auram"),			20)	.add(Aspect.getAspect("alienis"),		16)	.add(Aspect.getAspect("lucrum"),		20)	.add(Aspect.getAspect("metallum"),		8)	.add(Aspect.getAspect("praecantatio"),	50)	.add(Aspect.getAspect("potentia"),		16)	);	// Mauftrium
		ThaumcraftApi.registerObjectTag(new ItemStack(elvenResource, 1, 4),		(new AspectList())	.add(Aspect.getAspect("auram"),			10)	.add(Aspect.getAspect("alienis"),		8) 	.add(Aspect.getAspect("lucrum"),		10)	.add(Aspect.getAspect("metallum"),		4)	.add(Aspect.getAspect("praecantatio"),	20)	.add(Aspect.getAspect("ignis"),			24)	);	// Fire ingot
		ThaumcraftApi.registerObjectTag(new ItemStack(elvenResource, 1, 5),		(new AspectList())	.add(Aspect.getAspect("auram"),			10)	.add(Aspect.getAspect("alienis"),		8) 	.add(Aspect.getAspect("lucrum"),		10)	.add(Aspect.getAspect("metallum"),		4)	.add(Aspect.getAspect("praecantatio"),	20)	.add(Aspect.getAspect("gelum"),			24)	);	// Ice ingot
		ThaumcraftApi.registerObjectTag(new ItemStack(elvenResource, 1, 6),		(new AspectList())	.add(Aspect.getAspect("lucrum"),		1)	.add(Aspect.getAspect("metallum"),		1) 	.add(Aspect.getAspect("praecantatio"),	2)	);																																		// Elv nugg
		ThaumcraftApi.registerObjectTag(new ItemStack(elvenResource, 1, 7),		(new AspectList())	.add(Aspect.getAspect("auram"),			2)	.add(Aspect.getAspect("alienis"),		2) 	.add(Aspect.getAspect("lucrum"),		2)	.add(Aspect.getAspect("metallum"),		1)	.add(Aspect.getAspect("praecantatio"),	5)	.add(Aspect.getAspect("potentia"),		2)	);	// Mau nugg
		ThaumcraftApi.registerObjectTag(new ItemStack(elvenResource, 1, 8),		(new AspectList())	.add(Aspect.getAspect("auram"),			4)	.add(Aspect.getAspect("alienis"),		3) 	.add(Aspect.getAspect("lucrum"),		3)	.add(Aspect.getAspect("praecantatio"),	5)	.add(Aspect.getAspect("ignis"),			8)	);												// Fire ess
		ThaumcraftApi.registerObjectTag(new ItemStack(elvenResource, 1, 9),		(new AspectList())	.add(Aspect.getAspect("auram"),			4)	.add(Aspect.getAspect("alienis"),		3) 	.add(Aspect.getAspect("lucrum"),		3)	.add(Aspect.getAspect("praecantatio"),	5)	.add(Aspect.getAspect("gelum"),			8)	);												// Ice ess
		ThaumcraftApi.registerObjectTag(new ItemStack(elvenResource, 1, 10),	(new AspectList())	.add(Aspect.getAspect("auram"),			1)	.add(Aspect.getAspect("potentia"),		1) 	.add(Aspect.getAspect("praecantatio"),	1)	);																																		// Iffesal dust
		ThaumcraftApi.registerObjectTag(new ItemStack(elvenResource, 1, 11),	(new AspectList())	.add(Aspect.getAspect("auram"),			12)	.add(Aspect.getAspect("lucrum"),		6) 	.add(Aspect.getAspect("praecantatio"),	64)	.add(Aspect.getAspect("terra"),			8)	);																							// Prim rune
		ThaumcraftApi.registerObjectTag(new ItemStack(elvenResource, 1, 12),	(new AspectList())	.add(Aspect.getAspect("auram"),			3)	.add(Aspect.getAspect("praecantatio"),	16)	.add(Aspect.getAspect("terra"),			2)	.add(Aspect.getAspect("ignis"),			12)	);																							// Fire rune
		ThaumcraftApi.registerObjectTag(new ItemStack(elvenResource, 1, 13),	(new AspectList())	.add(Aspect.getAspect("auram"),			3)	.add(Aspect.getAspect("praecantatio"),	16)	.add(Aspect.getAspect("terra"),			2)	.add(Aspect.getAspect("gelum"),			12)	);																							// Ice rune
		ThaumcraftApi.registerObjectTag(new ItemStack(elvenResource, 1, 14),	(new AspectList())	.add(Aspect.getAspect("arbor"),			1)	.add(Aspect.getAspect("praecantatio"),	2)	);																							// Twig
		ThaumcraftApi.registerObjectTag(new ItemStack(elementalHelmet),			(new AspectList())	.add(Aspect.getAspect("metallum"),		15)	.add(Aspect.getAspect("praecantatio"),	12)	.add(Aspect.getAspect("tutamen"),		5)	.add(Aspect.getAspect("aqua"),			8)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(elementalHelmetRevealing),(new AspectList())	.add(Aspect.getAspect("metallum"),		15)	.add(Aspect.getAspect("praecantatio"),	12)	.add(Aspect.getAspect("tutamen"),		5)	.add(Aspect.getAspect("aqua"),			8)	.add(Aspect.getAspect("sensus"),		4)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(elementalChestplate),		(new AspectList())	.add(Aspect.getAspect("metallum"),		24)	.add(Aspect.getAspect("praecantatio"),	18)	.add(Aspect.getAspect("tutamen"),		8)	.add(Aspect.getAspect("terra"),			8)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(elementalLeggings),		(new AspectList())	.add(Aspect.getAspect("metallum"),		21)	.add(Aspect.getAspect("praecantatio"),	16)	.add(Aspect.getAspect("tutamen"),		7)	.add(Aspect.getAspect("ignis"),			8)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(elementalBoots),			(new AspectList())	.add(Aspect.getAspect("metallum"),		12)	.add(Aspect.getAspect("praecantatio"),	10)	.add(Aspect.getAspect("tutamen"),		4)	.add(Aspect.getAspect("aer"),			8)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(elvoriumHelmet),			(new AspectList())	.add(Aspect.getAspect("auram"),			12)	.add(Aspect.getAspect("metallum"),		35)	.add(Aspect.getAspect("praecantatio"),	64)	.add(Aspect.getAspect("tutamen"),		15)	.add(Aspect.getAspect("potentia"),		16)	.add(Aspect.getAspect("lucrum"),		30)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(elvoriumHelmetRevealing),	(new AspectList())	.add(Aspect.getAspect("auram"),			12)	.add(Aspect.getAspect("metallum"),		35)	.add(Aspect.getAspect("praecantatio"),	64)	.add(Aspect.getAspect("tutamen"),		15)	.add(Aspect.getAspect("potentia"),		16)	.add(Aspect.getAspect("lucrum"),		30)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(elvoriumChestplate),		(new AspectList())	.add(Aspect.getAspect("auram"),			12)	.add(Aspect.getAspect("metallum"),		56)	.add(Aspect.getAspect("praecantatio"),	64)	.add(Aspect.getAspect("tutamen"),		24)	.add(Aspect.getAspect("potentia"),		16)	.add(Aspect.getAspect("lucrum"),		30)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(elvoriumLeggings),		(new AspectList())	.add(Aspect.getAspect("auram"),			12)	.add(Aspect.getAspect("metallum"),		49)	.add(Aspect.getAspect("praecantatio"),	64)	.add(Aspect.getAspect("tutamen"),		21)	.add(Aspect.getAspect("potentia"),		16)	.add(Aspect.getAspect("lucrum"),		30)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(elvoriumBoots),			(new AspectList())	.add(Aspect.getAspect("auram"),			12)	.add(Aspect.getAspect("metallum"),		28)	.add(Aspect.getAspect("praecantatio"),	64)	.add(Aspect.getAspect("tutamen"),		12)	.add(Aspect.getAspect("potentia"),		16)	.add(Aspect.getAspect("lucrum"),		30)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(realitySword),			(new AspectList())	.add(Aspect.getAspect("auram"),			54)	.add(Aspect.getAspect("lucrum"),		49)	.add(Aspect.getAspect("metallum"),		18)	.add(Aspect.getAspect("potentia"),		36)	.add(Aspect.getAspect("praecantatio"),	64)	.add(Aspect.getAspect("telum"),			12)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(livingrockPickaxe),		(new AspectList())	.add(Aspect.getAspect("arbor"),			1)	.add(Aspect.getAspect("perditio"),		2)	.add(Aspect.getAspect("perfodio"),		2)	.add(Aspect.getAspect("terra"),			2)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(manasteelHoe),			(new AspectList())	.add(Aspect.getAspect("meto"),			4)	.add(Aspect.getAspect("metallum"),		6)	.add(Aspect.getAspect("praecantatio"),	1)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(elementiumHoe),			(new AspectList())	.add(Aspect.getAspect("meto"),			4)	.add(Aspect.getAspect("metallum"),		6)	.add(Aspect.getAspect("praecantatio"),	4)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(rodFire),					(new AspectList())	.add(Aspect.getAspect("auram"),			32)	.add(Aspect.getAspect("praecantatio"),	64)	.add(Aspect.getAspect("potentia"),		24)	.add(Aspect.getAspect("instrumentum"),	8)	.add(Aspect.getAspect("metallum"),		8)	.add(Aspect.getAspect("ignis"),			16)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(rodIce),					(new AspectList())	.add(Aspect.getAspect("auram"),			32)	.add(Aspect.getAspect("praecantatio"),	64)	.add(Aspect.getAspect("potentia"),		24)	.add(Aspect.getAspect("instrumentum"),	8)	.add(Aspect.getAspect("metallum"),		8)	.add(Aspect.getAspect("gelum"),			16)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(excaliber),				(new AspectList())	.add(Aspect.getAspect("motus"),			16)	.add(Aspect.getAspect("potentia"),		16)	.add(Aspect.getAspect("praecantatio"),	16)	.add(Aspect.getAspect("telum"),			16)	);	
		ThaumcraftApi.registerObjectTag(new ItemStack(mask),					(new AspectList())	.add(Aspect.getAspect("alienis"),		16)	.add(Aspect.getAspect("fames"),			16)	.add(Aspect.getAspect("sano"),			16)	.add(Aspect.getAspect("tenebrae"),		16)	.add(Aspect.getAspect("tutamen"),		16)	.add(Aspect.getAspect("vacuos"),		16)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(flugelSoul),				(new AspectList())	.add(Aspect.getAspect("auram"),			16)	.add(Aspect.getAspect("alienis"),		16)	.add(Aspect.getAspect("iter"),			16)	.add(Aspect.getAspect("ordo"),			16)	.add(Aspect.getAspect("praecantatio"),	16)	.add(Aspect.getAspect("spiritus"),		16)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(flugelDisc),				(new AspectList())	.add(Aspect.getAspect("aer"),			4)	.add(Aspect.getAspect("lucrum"),		4)	.add(Aspect.getAspect("sensus"),		4)	.add(Aspect.getAspect("lux"),			2)	.add(Aspect.getAspect("auram"),			2)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(elfFirePendant),			(new AspectList())	.add(Aspect.getAspect("praecantatio"),	24)	.add(Aspect.getAspect("auram"),			8)	.add(Aspect.getAspect("tutamen"),		6)	.add(Aspect.getAspect("ignis"),			8)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(elfIcePendant),			(new AspectList())	.add(Aspect.getAspect("praecantatio"),	24)	.add(Aspect.getAspect("auram"),			8)	.add(Aspect.getAspect("tutamen"),		6)	.add(Aspect.getAspect("gelum"),			8)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(pixieAttractor),			(new AspectList())	.add(Aspect.getAspect("praecantatio"),	12)	.add(Aspect.getAspect("metallum"),		12)	.add(Aspect.getAspect("vitreus"),		4)	.add(Aspect.getAspect("fames"),			2)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(creativeReachPendant),	(new AspectList())	.add(Aspect.getAspect("aer"),			64)	.add(Aspect.getAspect("aqua"),			64)	.add(Aspect.getAspect("ignis"),			64)	.add(Aspect.getAspect("ordo"),			64)	.add(Aspect.getAspect("perditio"),		64)	.add(Aspect.getAspect("terra"),			64)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(manaStone),				(new AspectList())	.add(Aspect.getAspect("auram"),			4)	.add(Aspect.getAspect("potentia"),		4)	.add(Aspect.getAspect("praecantatio"),	10)	.add(Aspect.getAspect("vitreus"),		4)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(manaStoneGreater),		(new AspectList())	.add(Aspect.getAspect("auram"),			12)	.add(Aspect.getAspect("potentia"),		4)	.add(Aspect.getAspect("praecantatio"),	20)	.add(Aspect.getAspect("vitreus"),		4)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(manaRingElven),			(new AspectList())	.add(Aspect.getAspect("auram"),			4)	.add(Aspect.getAspect("metallum"),		12)	.add(Aspect.getAspect("praecantatio"),	30)	.add(Aspect.getAspect("vitreus"),		4)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(manaRingGod),				(new AspectList())	.add(Aspect.getAspect("auram"),			32)	.add(Aspect.getAspect("metallum"),		24)	.add(Aspect.getAspect("potentia"),		24)	.add(Aspect.getAspect("praecantatio"),	64)	.add(Aspect.getAspect("vitreus"),		4)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(auraRingElven),			(new AspectList())	.add(Aspect.getAspect("auram"),			4)	.add(Aspect.getAspect("lucrum"),		4)	.add(Aspect.getAspect("metallum"),		12)	.add(Aspect.getAspect("praecantatio"),	16)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(auraRingGod),				(new AspectList())	.add(Aspect.getAspect("auram"),			16)	.add(Aspect.getAspect("alienis"),		4)	.add(Aspect.getAspect("lucrum"),		8)	.add(Aspect.getAspect("metallum"),		16)	.add(Aspect.getAspect("potentia"),		12)	.add(Aspect.getAspect("praecantatio"),	40)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(peacePipe), 				(new AspectList())	.add(Aspect.getAspect("spiritus"),		4)	.add(Aspect.getAspect("arbor"),			2)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(paperBreak), 				(new AspectList())	.add(Aspect.getAspect("spiritus"),		4)	.add(Aspect.getAspect("sensus"),		2)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(AlfheimItems.flugelHead),	(new AspectList())	.add(Aspect.getAspect("alienis"),		8)	.add(Aspect.getAspect("humanus"),		4)	.add(Aspect.getAspect("mortuus"),		8)	.add(Aspect.getAspect("spiritus"),		16)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(astrolabe),				(new AspectList())	.add(Aspect.getAspect("instrumentum"),	4)	.add(Aspect.getAspect("iter"),			2)	.add(Aspect.getAspect("metallum"),		8)	.add(Aspect.getAspect("praecantatio"),	6)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(invisibilityCloak),		(new AspectList())	.add(Aspect.getAspect("pannus"),		6)	.add(Aspect.getAspect("fabrico"),		1)	.add(Aspect.getAspect("sensus"),		4)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(dodgeRing),				(new AspectList())	.add(Aspect.getAspect("vitreus"),		3)	.add(Aspect.getAspect("metallum"),		8)	.add(Aspect.getAspect("lucrum"),		3)	.add(Aspect.getAspect("motus"),			6)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(lootInterceptor),			(new AspectList())	.add(Aspect.getAspect("praecantatio"),	5)	.add(Aspect.getAspect("metallum"),		4)	.add(Aspect.getAspect("auram"),			2)	.add(Aspect.getAspect("potentia"),		2)	.add(Aspect.getAspect("fames"),			16)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(rodGrass),				(new AspectList())	.add(Aspect.getAspect("herba"),			7)	.add(Aspect.getAspect("terra"),			3)	.add(Aspect.getAspect("sano"),			2)	.add(Aspect.getAspect("praecantatio"),	2)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(cloudPendant),			(new AspectList())	.add(Aspect.getAspect("tempestas"),		2)	.add(Aspect.getAspect("volatus"),		4)	.add(Aspect.getAspect("motus"),			4)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(cloudPendantSuper),		(new AspectList())	.add(Aspect.getAspect("tempestas"),		2)	.add(Aspect.getAspect("volatus"),		6)	.add(Aspect.getAspect("motus"),			8)	);
		
		// For transmutation recipe
		ThaumcraftApi.registerObjectTag(new ItemStack(manaResource, 1, 7),		(new AspectList())	.add(Aspect.getAspect("metallum"),		3)	.add(Aspect.getAspect("praecantatio"), 2)	);
		ThaumcraftApi.registerObjectTag(new ItemStack(manaResource, 1, 19),		(new AspectList())	.add(Aspect.getAspect("metallum"),		1)	.add(Aspect.getAspect("praecantatio"), 1)	);
	}
}
